<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Ape.Module.DeviceManager</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Ape.Core\Ape.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" Version="3.1.4" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="HidSharp" Version="2.1.0" />
    <PackageReference Include="System.IO.Ports" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Ape.Module.DeviceManager.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Tests/**" />
    <None Remove="Tests/**" />
  </ItemGroup>

</Project>
