<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <RootNamespace>Ape.Module.DeviceManager.Plugin.DeviceExample</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../../Ape.Core/Ape.Core.csproj">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </ProjectReference>
    <ProjectReference Include="../../Ape.Module.DeviceManager.csproj">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </ProjectReference>
  </ItemGroup>
</Project>
